[build]
target = "armv7a-none-eabi"

[target.armv7a-none-eabi]
runner = "qemu-system-arm -machine vexpress-a9 -serial mon:stdio -audiodev id=audio0,driver=sdl -audio sdl -kernel"
linker = "arm-none-eabi-gcc"
rustflags = [
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-Tkernel.ld",
    "-Zlocation-detail=none",
]
